language: clojure
services:
  - docker
cache:
  directories:
    - ~/.m2
jdk:
  - oraclejdk8
env:
  - DOCKER=stable
  - DOCKER=edge
  - DOCKER=rc
  - DOCKER=1.13.0
install:
  - bash dev/script/start-dind.sh
script:
  - lein test :all
  - lein with-profile prod uberjar
  - docker build -t swarmpit .
after_success:
  - bash dev/script/deploy-image.sh