language: clojure
services:
  - docker
cache:
  directories:
    - ~/.m2
jdk:
  - oraclejdk8
env:
  - DOCKER=test
  - DOCKER=stable
  - DOCKER=17.05
  - DOCKER=17.04
  - DOCKER=17.03
  - DOCKER=1.13.0
install:
  - bash dev/script/init-db.sh
  - bash dev/script/start-dind.sh
script:
  - lein test :all
after_success:
  - bash dev/script/deploy-image.sh