language: clojure
fail_fast: true
services:
  - docker
cache:
  directories:
    - ~/.m2
jdk:
  - oraclejdk8
script:
  - lein test
  - lein with-profile prod uberjar
  - docker build -t swarmpit .
  - bash dev/script/deploy-image.sh